site_name: PetitGato
site_author: Seu Nome
site_url: https://github.com/Xiristian/PetitGato.git
site_description: Documentação do Projeto de Data Lake com base em metodologias ativas de aprendizagem

repo_name: PetitGato
repo_url: https://github.com/Xiristian/PetitGato.git

nav:
  - Home: index.md
  - Introdução: introduction.md
  - Configuração Terraform e Datalake: azure-data-lake-terraform.md
  - Configuração Inicial do Ambiente: environment_setup.md
  - Ambiente Relacional - Origem: data_sources.md
  - Ingestão de Dados: ingestion.md
  - Transformação de Dados com Apache Spark: transformation.md
  - Arquitetura do Data Lake: data_lake_architecture.md
  - Armazenamento em Object Storage: object_storage.md
  - Modelo Dimensional ou OBT: dimensional_model.md
  - Dashboard e Visualização: dashboard.md
  - Tecnologias Utilizadas: technologies.md
  - Gestão do Projeto no GitHub: github_management.md
  - Apresentação e Entrega: presentation_delivery.md
  - Conclusão: conclusion.md


theme:
  name: material
  palette:
    primary: blue grey 
    accent: light-blue
  language: pt
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - search
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css


plugins:
  - search
