site_name: Petit Gato
site_author: Luz Brenda, Julia de Luca
site_url: https://github.com/Xiristian/PetitGato.git
site_description: Documentação do Projeto de Data Lake com base em metodologias ativas de aprendizagem
site_favicon: images/favicon.png
site_logo: images/logo.png
site_keywords: Engenharia de Dados, Engenharia de Software, SATC, Python, Pyspark, Delta, Jupyter, Git, GitHub, Markdown, MkDocs, Material Theme

repo_name: PetitGato
repo_url: https://github.com/Xiristian/PetitGato.git
edit_uri: edit/master/docs/

docs_dir: docs

nav:
  - Home: index.md
  - Introdução: introduction.md
  - Visão Geral do PipeLine: overview.md 
  - Configuração Terraform e Datalake: azure-data-lake-terraform.md
  - Configuração Inicial do Ambiente: environment_setup.md
  - Ingestão de Dados: ingestion.md
  - Transformação de Dados com Apache Spark: transformation.md
  - Modelo Dimensional: dimensional_model.md
  - Contribuidores: contribuitors.md


theme:
  name: material
  palette:
    primary: brown
  language: pt
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - search
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css


plugins:
  - search


copyright: Copyright &copy; 2024 - <a href="#" target="_blank"><b>JACAL</b></a> - Todos os direitos reservados.