site_name: PetitGato
site_url: https://mydomain.org/mysite
site_keywords: Engenharia de Dados, Engenharia de Software, SATC, Python, Pyspark, Delta, Jupyter, Git, GitHub, Markdown, MkDocs, Material Theme

theme:
  name: material  
  palette:
    primary: blue-grey
  language: pt
 # features:
 #   - navigation.instant
 #  - navigation.instant.progress

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings:
      default_handler: python


